### ISSUE TITLE
do not force using requirements folder

### ISSUE THREAD

**Issue by gsemet** [level12/wheelhouse#8]
Hello

It is pretty unusual to force users to define their requirements in a `requirements` folder. Please let user have their requirements.txt in the root folder or anywhere else

Thanks

**Comment by rsyring** [comment]
I think this is a default, not forced.  It's likely it can be worked around with relative paths in the config ('../requirements.txt') or setting a config to change the default path.  I don't remember off the top of my head and I don't have time to look right now, but just wanted to throw this out there in case you wanted to investigate further.

**Comment by kierun** [comment]
How do you set "a config to change the default path."?… It is not clear at all and I cannot find it in the documentation. Off to read source code. ☹

**Comment by kierun** [comment]
Found them:

```
requirements_path = tox
requirement_files = requirements-pinned.txt
wheelhouse_path = tox/wheelhouse
```

… For posterity.
